In [2]:
#numpy works on HOMOGENOUS data
import numpy as np

In [3]:
arr=np.array([2,7,10,13,26])
arr

array([ 2,  7, 10, 13, 26])

In [4]:
arr2 = np.array([[2,7,10],[10,13,26]])
arr2

array([[ 2,  7, 10],
       [10, 13, 26]])

In [5]:
arr.ndim
#to check tghe dimension of that aray

1

In [6]:
arr2.ndim

2

In [7]:
arr3 = np.array([[[1,2,3]],[[1,2,3]],[[4,9,0]]])

In [8]:
arr3
arr3.ndim

3

In [9]:
arr3

array([[[1, 2, 3]],

       [[1, 2, 3]],

       [[4, 9, 0]]])

In [10]:
new_arr3 = np.array([[[178, 189, 567], [145, 239, 445], [197, 345, 678]],
                [[56, 78, 190], [46, 10, 11], [6, 2, 1]],
                [[45, 118, 203], [72, 119, 34], [87, 9, 5]]])

In [11]:
new_arr3

array([[[178, 189, 567],
        [145, 239, 445],
        [197, 345, 678]],

       [[ 56,  78, 190],
        [ 46,  10,  11],
        [  6,   2,   1]],

       [[ 45, 118, 203],
        [ 72, 119,  34],
        [ 87,   9,   5]]])

In [12]:
new_arr3.ndim

3

In [13]:
arr2

array([[ 2,  7, 10],
       [10, 13, 26]])

In [14]:
#slicing on 2d & 3d array
#indexing
arr2[0,2]

10

In [15]:
#slicing
arr2[1,0:2]

array([10, 13])

In [16]:
arr3=np.array([[[1,23,33],[2,22,54],[5,6,8]],[[10,20,30],[25,22,55],[50,60,80]]])

In [17]:
#indexing on 3d array
arr3

array([[[ 1, 23, 33],
        [ 2, 22, 54],
        [ 5,  6,  8]],

       [[10, 20, 30],
        [25, 22, 55],
        [50, 60, 80]]])

In [18]:
arr3[1,2,0]
# matrix,row,column

50

In [19]:
arr3[1,2,0:3]

array([50, 60, 80])

In [20]:
arr3[0,1,2]

54

In [21]:
arr3[1,1,1:3]

array([22, 55])

In [25]:
temperature_data = [25.3, 26.1, 24.8, 23.5, 27.2]
pressure_data = [101.2, 100.8, 101.5, 100.2, 101.0]
humidity_data = [55.2, 54.8, 56.5, 53.7, 55.9]

In [26]:
#create a numpy array from the dataset
temperature_array = np.array(temperature_data)
pressure_array = np.array(pressure_data)
humidity_array = np.array(humidity_data)

In [27]:
#calculte the mean(avg) of each activity
t_mean = np.mean(temperature_array)
p_mean = np.mean(pressure_array)
h_mean = np.mean(humidity_array)

In [28]:
#calculate the standard deviation of each quantity
t_sd = np.std(temperature_array)
p_sd = np.std(pressure_array)
h_sd = np.std(humidity_array)

In [31]:
t_sd

1.2416118556135003

In [32]:
t_max = np.amax(temperature_array)
p_max = np.amax(pressure_array)
h_max = np.amax(humidity_array)
t_min = np.amin(temperature_array)
p_min = np.amin(pressure_array)
h_min = np.amin(humidity_array)

In [33]:
print(t_max,t_min)

27.2 23.5
